use_frameworks!

target 'SupportIm_Example', :exclusive => true do
  pod 'SupportIm', :path => '../'
end

target 'SupportIm_Tests', :exclusive => true do
  pod 'SupportIm', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
